/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  BitbucketRepoTreeNode,
} from './utils/bitbucket';

export namespace Components {
  interface D2Audit {
    'branch': string;
    'brand': string;
    'project': string;
    'repo': string;
  }
  interface D2AuditBranches {
    'project': string;
    'repo': string;
  }
  interface D2AuditBrands {
    'project': string;
  }
  interface D2AuditRepos {
    'project': string;
  }
  interface D2AuditResults {
    'branch': string;
    'brand': string;
    'project': string;
    'repo': string;
    'tree': BitbucketRepoTreeNode[];
  }
}

declare global {


  interface HTMLD2AuditElement extends Components.D2Audit, HTMLStencilElement {}
  var HTMLD2AuditElement: {
    prototype: HTMLD2AuditElement;
    new (): HTMLD2AuditElement;
  };

  interface HTMLD2AuditBranchesElement extends Components.D2AuditBranches, HTMLStencilElement {}
  var HTMLD2AuditBranchesElement: {
    prototype: HTMLD2AuditBranchesElement;
    new (): HTMLD2AuditBranchesElement;
  };

  interface HTMLD2AuditBrandsElement extends Components.D2AuditBrands, HTMLStencilElement {}
  var HTMLD2AuditBrandsElement: {
    prototype: HTMLD2AuditBrandsElement;
    new (): HTMLD2AuditBrandsElement;
  };

  interface HTMLD2AuditReposElement extends Components.D2AuditRepos, HTMLStencilElement {}
  var HTMLD2AuditReposElement: {
    prototype: HTMLD2AuditReposElement;
    new (): HTMLD2AuditReposElement;
  };

  interface HTMLD2AuditResultsElement extends Components.D2AuditResults, HTMLStencilElement {}
  var HTMLD2AuditResultsElement: {
    prototype: HTMLD2AuditResultsElement;
    new (): HTMLD2AuditResultsElement;
  };
  interface HTMLElementTagNameMap {
    'd2-audit': HTMLD2AuditElement;
    'd2-audit-branches': HTMLD2AuditBranchesElement;
    'd2-audit-brands': HTMLD2AuditBrandsElement;
    'd2-audit-repos': HTMLD2AuditReposElement;
    'd2-audit-results': HTMLD2AuditResultsElement;
  }
}

declare namespace LocalJSX {
  interface D2Audit extends JSXBase.HTMLAttributes<HTMLD2AuditElement> {
    'branch'?: string;
    'brand'?: string;
    'project'?: string;
    'repo'?: string;
  }
  interface D2AuditBranches extends JSXBase.HTMLAttributes<HTMLD2AuditBranchesElement> {
    'onChangebranch'?: (event: CustomEvent<any>) => void;
    'project'?: string;
    'repo'?: string;
  }
  interface D2AuditBrands extends JSXBase.HTMLAttributes<HTMLD2AuditBrandsElement> {
    'onChangebrand'?: (event: CustomEvent<any>) => void;
    'project'?: string;
  }
  interface D2AuditRepos extends JSXBase.HTMLAttributes<HTMLD2AuditReposElement> {
    'onChangerepo'?: (event: CustomEvent<any>) => void;
    'project'?: string;
  }
  interface D2AuditResults extends JSXBase.HTMLAttributes<HTMLD2AuditResultsElement> {
    'branch'?: string;
    'brand'?: string;
    'project'?: string;
    'repo'?: string;
    'tree'?: BitbucketRepoTreeNode[];
  }

  interface IntrinsicElements {
    'd2-audit': D2Audit;
    'd2-audit-branches': D2AuditBranches;
    'd2-audit-brands': D2AuditBrands;
    'd2-audit-repos': D2AuditRepos;
    'd2-audit-results': D2AuditResults;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


