/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  BitbucketRepoTreeJsonType,
} from './utils/types/BitbucketTypes';

export namespace Components {
  interface D2Audit {
    'branch': string;
    'brand': string;
    'repo': string;
    'treeUrl': string;
  }
  interface D2AuditBranches {}
  interface D2AuditRepos {}
  interface D2AuditResults {
    'brand': string;
    'tree': BitbucketRepoTreeJsonType[];
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLD2AuditElement extends Components.D2Audit, HTMLStencilElement {}
  var HTMLD2AuditElement: {
    prototype: HTMLD2AuditElement;
    new (): HTMLD2AuditElement;
  };

  interface HTMLD2AuditBranchesElement extends Components.D2AuditBranches, HTMLStencilElement {}
  var HTMLD2AuditBranchesElement: {
    prototype: HTMLD2AuditBranchesElement;
    new (): HTMLD2AuditBranchesElement;
  };

  interface HTMLD2AuditReposElement extends Components.D2AuditRepos, HTMLStencilElement {}
  var HTMLD2AuditReposElement: {
    prototype: HTMLD2AuditReposElement;
    new (): HTMLD2AuditReposElement;
  };

  interface HTMLD2AuditResultsElement extends Components.D2AuditResults, HTMLStencilElement {}
  var HTMLD2AuditResultsElement: {
    prototype: HTMLD2AuditResultsElement;
    new (): HTMLD2AuditResultsElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'd2-audit': HTMLD2AuditElement;
    'd2-audit-branches': HTMLD2AuditBranchesElement;
    'd2-audit-repos': HTMLD2AuditReposElement;
    'd2-audit-results': HTMLD2AuditResultsElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface D2Audit extends JSXBase.HTMLAttributes<HTMLD2AuditElement> {
    'branch'?: string;
    'brand'?: string;
    'repo'?: string;
    'treeUrl'?: string;
  }
  interface D2AuditBranches extends JSXBase.HTMLAttributes<HTMLD2AuditBranchesElement> {
    'onChangeBranch'?: (event: CustomEvent<any>) => void;
  }
  interface D2AuditRepos extends JSXBase.HTMLAttributes<HTMLD2AuditReposElement> {
    'onChangeRepo'?: (event: CustomEvent<any>) => void;
  }
  interface D2AuditResults extends JSXBase.HTMLAttributes<HTMLD2AuditResultsElement> {
    'brand'?: string;
    'tree'?: BitbucketRepoTreeJsonType[];
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'd2-audit': D2Audit;
    'd2-audit-branches': D2AuditBranches;
    'd2-audit-repos': D2AuditRepos;
    'd2-audit-results': D2AuditResults;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


